/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Unit_converter;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author nhami
 */
public class Unit_Converter extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Unit_Converter.class.getName());

    /**
     * Creates new form Unit_Converter
     */
    private DecimalFormat df = new DecimalFormat("#.######");
    
    // Units for each category
    private String[][] units = {
        {"Length", "Meter", "Kilometer", "Centimeter", "Millimeter", "Mile", "Yard", "Foot", "Inch"},
        {"Weight", "Kilogram", "Gram", "Milligram", "Pound", "Ounce", "Ton"},
        {"Temperature", "Celsius", "Fahrenheit", "Kelvin"},
        {"Volume", "Liter", "Milliliter", "Gallon", "Quart", "Pint", "Cup"},
        {"Speed", "Meter/Second", "Kilometer/Hour", "Mile/Hour", "Knot"},
        {"Time", "Second", "Minute", "Hour", "Day", "Week", "Month", "Year"}
    };
    
    
    public Unit_Converter() {
        initComponents();
        setLocationRelativeTo(null);
        updateUnitComboBoxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        lblTo = new javax.swing.JLabel();
        cmbToUnit = new javax.swing.JComboBox<>();
        lblResult = new javax.swing.JLabel();
        txtOutput = new javax.swing.JTextField();
        lblFrom = new javax.swing.JLabel();
        cmbFromUnit = new javax.swing.JComboBox<>();
        lblValue = new javax.swing.JLabel();
        textInput = new javax.swing.JTextField();
        btnSwap = new javax.swing.JButton();
        btnConvert = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unit Converter");
        setPreferredSize(new java.awt.Dimension(600, 500));

        jPanel2.setBackground(new java.awt.Color(99, 197, 218));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 500));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Unit Converter");
        lblTitle.setToolTipText("");

        lblCategory.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategory.setText("Category:");

        cmbCategory.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Length", "Weight", "Temperature", "Volume", "Speed", "Time" }));
        cmbCategory.addActionListener(this::cmbCategoryActionPerformed);

        lblTo.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        lblTo.setText("To:");

        cmbToUnit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cmbToUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblResult.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblResult.setText("Result:");

        txtOutput.setColumns(15);
        txtOutput.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lblFrom.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        lblFrom.setText("From:");

        cmbFromUnit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cmbFromUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblValue.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblValue.setText("Value:");

        textInput.setColumns(15);
        textInput.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnSwap.setBackground(new java.awt.Color(102, 102, 102));
        btnSwap.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSwap.setForeground(new java.awt.Color(255, 255, 255));
        btnSwap.setText("Swap");
        btnSwap.addActionListener(this::btnSwapActionPerformed);

        btnConvert.setBackground(new java.awt.Color(102, 102, 255));
        btnConvert.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnConvert.setText("Convert");
        btnConvert.addActionListener(this::btnConvertActionPerformed);

        btnClear.setBackground(new java.awt.Color(102, 0, 0));
        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textInput, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cmbFromUnit, 0, 186, Short.MAX_VALUE)
                                        .addGap(37, 37, 37)
                                        .addComponent(btnSwap)
                                        .addGap(27, 27, 27))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(lblFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbToUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblTo)
                                        .addGap(142, 142, 142)))
                                .addGap(22, 22, 22))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblValue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblResult)
                                .addGap(131, 131, 131)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConvert, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addGap(177, 177, 177))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCategory)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lblTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbToUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSwap)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbFromUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValue)
                            .addComponent(lblResult))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConvert)
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        // TODO add your handling code here:
    updateUnitComboBoxes();

    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        // TODO add your handling code here:
    convertUnits();
    }//GEN-LAST:event_btnConvertActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    // From aar To swap koro
    clearFields();
    
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSwapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwapActionPerformed
        // TODO add your handling code here:
    swapUnits();
    }//GEN-LAST:event_btnSwapActionPerformed

    // Custom Methods
    private void updateUnitComboBoxes() {
        int selectedCategory = cmbCategory.getSelectedIndex();
        cmbFromUnit.removeAllItems();
        cmbToUnit.removeAllItems();
        
        for (int i = 1; i < units[selectedCategory].length; i++) {
            cmbFromUnit.addItem(units[selectedCategory][i]);
            cmbToUnit.addItem(units[selectedCategory][i]);
        }
        
        if (cmbToUnit.getItemCount() > 1) {
            cmbToUnit.setSelectedIndex(1);
        }
    }
    
    private void swapUnits() {
        int fromIndex = cmbFromUnit.getSelectedIndex();
        int toIndex = cmbToUnit.getSelectedIndex();
        
        cmbFromUnit.setSelectedIndex(toIndex);
        cmbToUnit.setSelectedIndex(fromIndex);
        
        String temp = textInput.getText();
        textInput.setText(txtOutput.getText());

        txtOutput.setText(temp);
    }
    
    private void clearFields() {
        textInput.setText("");
        txtOutput.setText("");
    }
    
    private void convertUnits() {
        try {
            double input = Double.parseDouble(textInput.getText());
            String category = (String) cmbCategory.getSelectedItem();
            String fromUnit = (String) cmbFromUnit.getSelectedItem();
            String toUnit = (String) cmbToUnit.getSelectedItem();
            
            double result = performConversion(input, category, fromUnit, toUnit);
            txtOutput.setText(df.format(result));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number!", 
                "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private double performConversion(double value, String category, String from, String to) {
        double baseValue = 0;
        
        switch (category) {
            case "Length":
                baseValue = convertToBaseLength(value, from);
                return convertFromBaseLength(baseValue, to);
            case "Weight":
                baseValue = convertToBaseWeight(value, from);
                return convertFromBaseWeight(baseValue, to);
            case "Temperature":
                return convertTemperature(value, from, to);
            case "Volume":
                baseValue = convertToBaseVolume(value, from);
                return convertFromBaseVolume(baseValue, to);
            case "Speed":
                baseValue = convertToBaseSpeed(value, from);
                return convertFromBaseSpeed(baseValue, to);
            case "Time":
                baseValue = convertToBaseTime(value, from);
                return convertFromBaseTime(baseValue, to);
        }
        return value;
    }
    
    // Length conversions (base: meter)
    private double convertToBaseLength(double value, String unit) {
        switch (unit) {
            case "Meter": return value;
            case "Kilometer": return value * 1000;
            case "Centimeter": return value / 100;
            case "Millimeter": return value / 1000;
            case "Mile": return value * 1609.34;
            case "Yard": return value * 0.9144;
            case "Foot": return value * 0.3048;
            case "Inch": return value * 0.0254;
            default: return value;
        }
    }
    
    private double convertFromBaseLength(double value, String unit) {
        switch (unit) {
            case "Meter": return value;
            case "Kilometer": return value / 1000;
            case "Centimeter": return value * 100;
            case "Millimeter": return value * 1000;
            case "Mile": return value / 1609.34;
            case "Yard": return value / 0.9144;
            case "Foot": return value / 0.3048;
            case "Inch": return value / 0.0254;
            default: return value;
        }
    }
    
    // Weight conversions (base: kilogram)
    private double convertToBaseWeight(double value, String unit) {
        switch (unit) {
            case "Kilogram": return value;
            case "Gram": return value / 1000;
            case "Milligram": return value / 1000000;
            case "Pound": return value * 0.453592;
            case "Ounce": return value * 0.0283495;
            case "Ton": return value * 1000;
            default: return value;
        }
    }
    
    private double convertFromBaseWeight(double value, String unit) {
        switch (unit) {
            case "Kilogram": return value;
            case "Gram": return value * 1000;
            case "Milligram": return value * 1000000;
            case "Pound": return value / 0.453592;
            case "Ounce": return value / 0.0283495;
            case "Ton": return value / 1000;
            default: return value;
        }
    }
    
    // Temperature conversions
    private double convertTemperature(double value, String from, String to) {
        double celsius = 0;
        
        switch (from) {
            case "Celsius": celsius = value; break;
            case "Fahrenheit": celsius = (value - 32) * 5/9; break;
            case "Kelvin": celsius = value - 273.15; break;
        }
        
        switch (to) {
            case "Celsius": return celsius;
            case "Fahrenheit": return celsius * 9/5 + 32;
            case "Kelvin": return celsius + 273.15;
            default: return celsius;
        }
    }
    
    // Volume conversions (base: liter)
    private double convertToBaseVolume(double value, String unit) {
        switch (unit) {
            case "Liter": return value;
            case "Milliliter": return value / 1000;
            case "Gallon": return value * 3.78541;
            case "Quart": return value * 0.946353;
            case "Pint": return value * 0.473176;
            case "Cup": return value * 0.236588;
            default: return value;
        }
    }
    
    private double convertFromBaseVolume(double value, String unit) {
        switch (unit) {
            case "Liter": return value;
            case "Milliliter": return value * 1000;
            case "Gallon": return value / 3.78541;
            case "Quart": return value / 0.946353;
            case "Pint": return value / 0.473176;
            case "Cup": return value / 0.236588;
            default: return value;
        }
    }
    
    // Speed conversions (base: meter/second)
    private double convertToBaseSpeed(double value, String unit) {
        switch (unit) {
            case "Meter/Second": return value;
            case "Kilometer/Hour": return value / 3.6;
            case "Mile/Hour": return value * 0.44704;
            case "Knot": return value * 0.514444;
            default: return value;
        }
    }
    
    private double convertFromBaseSpeed(double value, String unit) {
        switch (unit) {
            case "Meter/Second": return value;
            case "Kilometer/Hour": return value * 3.6;
            case "Mile/Hour": return value / 0.44704;
            case "Knot": return value / 0.514444;
            default: return value;
        }
    }
    
    // Time conversions (base: second)
    private double convertToBaseTime(double value, String unit) {
        switch (unit) {
            case "Second": return value;
            case "Minute": return value * 60;
            case "Hour": return value * 3600;
            case "Day": return value * 86400;
            case "Week": return value * 604800;
            case "Month": return value * 2628000;
            case "Year": return value * 31536000;
            default: return value;
        }
    }
    
    private double convertFromBaseTime(double value, String unit) {
        switch (unit) {
            case "Second": return value;
            case "Minute": return value / 60;
            case "Hour": return value / 3600;
            case "Day": return value / 86400;
            case "Week": return value / 604800;
            case "Month": return value / 2628000;
            case "Year": return value / 31536000;
            default: return value;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
             java.util.logging.Logger.getLogger(Unit_Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Unit_Converter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnConvert;
    private javax.swing.JButton btnSwap;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbFromUnit;
    private javax.swing.JComboBox<String> cmbToUnit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTo;
    private javax.swing.JLabel lblValue;
    private javax.swing.JTextField textInput;
    private javax.swing.JTextField txtOutput;
    // End of variables declaration//GEN-END:variables
}
